# ruby=2.4.2
# ruby-gemset=rh_challenge
ruby '2.7.5'
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# core gems
gem 'json'
gem 'jbuilder'
gem 'mini_magick'
gem "paperclip"
gem 'puma'
gem 'rails', '>= 7.0.8.4'
gem 'therubyracer'
gem 'uglifier'
gem 'will_paginate'



gem 'binding_of_caller'
gem 'rails-i18n', '>= 7.0.7'
gem 'webpacker', '>= 5.4.4'
gem 'devise', '>= 4.9.0'
#gem 'letter_opener'
gem 'validators'
# Use postgresql as the database for Active Record
gem "pg"
# Google authentication
gem 'omniauth-google-oauth2'

# Google authentication
gem 'omniauth-rails_csrf_protection', '>= 1.0.2'


# frontend
gem 'bootstrap-sass'
gem 'bootstrap-will_paginate'
gem 'font-awesome-rails'
gem 'haml'
gem 'jquery-rails', '>= 4.6.0'
gem 'jquery-ui-rails', '>= 7.0.0'
gem 'simple_form', '>= 5.2.0'
gem 'cocoon'
gem 'sass-rails'
gem 'turbolinks'

# group :development, :test do
#   gem 'byebug'
#   gem 'faker'
#   gem 'pry-rails'
#   gem 'rubocop'
#   gem 'reek'
#   gem 'sqlite3'
# end

group :development do
  gem 'better_errors'
  gem 'web-console', '>= 4.2.1'
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
end

# group :test do
#   gem 'capybara'
#   gem 'poltergeist'
#   gem 'database_cleaner'
#   gem 'factory_bot_rails'
#   gem 'rspec-rails'
#   gem 'rspec-core'
#   gem 'rspec-collection_matchers'
#   gem 'rspec-mocks'
#   gem 'guard'
#   gem 'guard-rspec'
#   gem 'simplecov'
#   gem 'shoulda-matchers'
# end

group :production do

end
